spring:
  application:
    name: em-app-as
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/media_db}
    username: ${DB_USERNAME:media_db_user}
    password: ${DB_PASSWORD:media_db_pswd}
  devtools:
    add-properties: true
    livereload:
      enabled: true
      restart:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github: #https://github.com/settings/developers
            client-id: ${GITHUB_CLIENT_ID:Ov23liBNoJCrAK4844Xz}
            client-secret: ${GITHUB_CLIENT_SECRET:10ea9bcb13aa4d490278b8fe10f20c0c4ceb4e31}
            scope:
              - user:email
              - read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          tiktok:
            client-id: ${TIKTOK_CLIENT_ID}
            client-secret: ${TIKTOK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user.info.basic
        provider:
          tiktok:
            authorization-uri: https://www.tiktok.com/v2/auth/authorize/
            token-uri: https://open.tiktokapis.com/v2/oauth/token/
            user-info-uri: https://open.tiktokapis.com/v2/user/info/
            user-name-attribute: data.user.open_id

server:
  port: 8080

app:
  front.url: http://localhost:4200
  jwt:
    secret: ${JWT_SECRET:ABCD1234!@#$abcd?^kkkkkkkkkkuuuuuuuuuujghgfsssrfgtyhb}
    expiration: ${JWT_EXPIRATION:86400000}
  auth-success:
    redirect-uri: ${AUTH_SUCCESS_REDIRECT_URI:http://localhost:4200/auth/callback}

#https://springdoc.org/
springdoc:
  show-actuator: true
  swagger-ui:
    path: swagger-ui
