spring:
  application:
    name: media
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/media_db}
    username: ${DB_USERNAME:media_db_user}
    password: ${DB_PASSWORD:media_db_pswd}
  devtools:
    add-properties: true
    livereload:
      enabled: true
      restart:
        enabled: true

server:
  port: 8080


#https://springdoc.org/
springdoc:
  show-actuator: true
  swagger-ui:
    path: swagger-ui

